### ISSUE TITLE
advisories are out of sync.

### ISSUE THREAD

**Issue by gtanner** [nodesecurity/nodesecurity.io#53]
[web advistories](https://nodesecurity.io/advisories) !== [OSS advisories](https://github.com/nodesecurity/nodesecurity.io/tree/master/advisories)

Seems all of the advisories logged since Oct 20th have not shown up in this project.

**Comment by evilpacket** [comment]
This is correct. We currently do not manage sync between the markdown files and the database. Markdown files will be deprecated in short order.

**Comment by gtanner** [comment]
Where is the database and will the community still have access to read from it?

**Comment by evilpacket** [comment]
It's available for non commercial use. 

If you need commercial use or to redistribute please let me know privately.

You can access it via the new API. It's currently undocumented however we're working on docs.

Here is a quick and dirty doc https://gist.github.com/evilpacket/e3d4c743e380e68569fd
