### ISSUE TITLE
https://nodesecurity.io/advisories/48 fixed by uglify-js 2.6.0

### ISSUE THREAD

**Issue by ockham** [nodesecurity/nodesecurity.io#54]
Apologies if this is the entirely wrong place for reporting, but it seems as if https://nodesecurity.io/advisories/48 has been fixed as of uglify-js v2.6.0 (by mishoo/UglifyJS2@63d35f8, to be exact), while  nodesecurity.io and the `nsp` tool still report that there are no fixed versions available.

**Comment by evilpacket** [comment]
@ockham thanks for the heads up. Always great to get updated info. I've updated the advisory.
