### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by maxrimue** [nodesecurity/nodesecurity.io#58]
Hello, I was looking for an API to check for vulnerabilities in certain packages. In [an old blog post](https://blog.liftsecurity.io/2015/01/21/tooling#use-it-programmatically), the package [nsp-api](https://www.npmjs.com/package/nsp-api) is mentioned, however, the corresponding repository was deleted. Also, in the nsp repository, I've noticed [this line](https://github.com/nodesecurity/nsp/blob/master/lib/check.js#L10), which got me further confused. Which way is the right way to use your API? Thanks.

Update: I mentioned the nsp-api module also because in it, the URL `https://nodesecurity.io/validate/...` is used instead of something like `https://api.nodesecurity.io/...`

**Comment by evilpacket** [comment]
No that's old information. The nsp-api module is deprecated. 

Currently the api isn't intended to be consumed directly and is undocumented. We have more changes and features planned so the best way is to use the nsp client. The nsp client if required exposes methods that can be used to query the API.
